apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: radimcajzl/udacity-metrics-frontend:latest
        # TODO: change to Always and deploy the images online
        imagePullPolicy: Never
        ports:
        - name: web
          containerPort: 8080
        env:
          - name: JAEGER_HOST
            value: "jaeger-app-agent.default.svc.cluster.local"
          - name: JAEGER_PORT
            value: "6831"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      nodePort: 31080
  type: LoadBalancer